### ISSUE TITLE
Maybe you would like to actually put the name and date on the Apache License

### ISSUE THREAD

**Issue by koenichiwa** [frewsxcv/cargo-all-features#11]
And maybe MIT if you're not with georust

**Comment by frewsxcv** [comment]
oops! updated the mit license: https://github.com/frewsxcv/cargo-all-features/blob/master/LICENSE-MIT

in the apache license, the text at the bottom is not meant to be updated. the license is telling you what you can put at the top of the files

https://github.com/frewsxcv/cargo-all-features/blob/2c7509e76d562e040f187eed42b2861510505532/LICENSE-APACHE#L178-L187
