### ISSUE TITLE
It seems to work on optional dependencies, not on features - is this intended?

### ISSUE THREAD

**Issue by Byron** [frewsxcv/cargo-all-features#2]
How to reproduce (on MacOS, Rustc version 1.43.1, cargo-all-features version 1.2.0)

```sh
git clone https://github.com/crates-io/prodash
cd prodash
cargo build-all-features
```
<img width="563" alt="Screenshot 2020-05-26 at 17 16 46" src="https://user-images.githubusercontent.com/63622/82883187-af0b5680-9f74-11ea-8eb6-33bd52c89c77.png">

What's expected is that it only activates features, along with their dependencies:

<img width="374" alt="Screenshot 2020-05-26 at 17 17 16" src="https://user-images.githubusercontent.com/63622/82883303-d2360600-9f74-11ea-89bf-aacb0a6882d4.png">

It seems to activate optional dependencies instead, along with all their permutations.

**Comment by frewsxcv** [comment]
It should be running permutations of all optional dependencies _and_ features: https://github.com/frewsxcv/cargo-all-features/blob/master/src/features_finder.rs

I just ran your "How to reproduce" steps and it seems to be picking up the features. Are you interested in having it _not_ test optional dependencies?

**Comment by Byron** [comment]
Interesting! I never waited long enough to see it pick up features.
Indeed it was surprising to me given the name of the program, and I didn't know that valid features are also optional dependencies.

From my own experience, I think it would have been enough to only test features, and not optional dependencies. The latter would be nice at least to opt-out of.

**Comment by frewsxcv** [comment]
i included optional dependencies because i've seen cases in the rust ecosystem use optional dependencies like features. and conceptually, they're essentially feature flags you need to invoke with `--features <optional depedency>`. in any case: https://github.com/frewsxcv/cargo-all-features/issues/3
