### ISSUE TITLE
Support chunking

### ISSUE THREAD

**Issue by Manishearth** [frewsxcv/cargo-all-features#28]
This tool tends to fill up target directories really quickly. For large projects like ICU4X, this puts us in danger of hitting CI size limits. Furthermore, it just takes pretty long and it would be nice to be able to make use of parallelism.

A typical technique in CI systems is to support "chunking", where you have something like `--chunks 3 --chunk 1`, which splits the list of jobs into three chunks, and directs it to run just the jobs for the first one, so you can have the chunks get run on separate runners.

Thoughts?

**Comment by frewsxcv** [comment]
@Manishearth Do you know which aspect of compiling with different feature flags causes `target/` to fill up? I'm open to your suggestion, but also wonder if there's a way we can clean up some files between runs.

**Comment by Manishearth** [comment]
I'm not sure! I upgraded rustc a couple versions in https://github.com/unicode-org/icu4x/pull/1783 and suddenly disk space usage for the feature task has more than doubled (I don't have the exact numbers since i'm still waiting for the job to complete)

I suspect it's codegen unit stuff or whatever. But I'm still investigating. Probably I'll try to measure this for a normal build first instead of all-features which takes forever.

For now I've also switched over to using `check-all-features`, which should be at least a _bit_ better.

**Comment by Manishearth** [comment]
You could use `cargo build -v --message-format=json` and delete selected binaries but it's fiddly and you also kinda want stuff to be cached.

**Comment by frewsxcv** [comment]
What about something like:

```
cargo build

cp -R target target-cached

for features in feature_flag_combinations:
    cargo build --features features
    rm -rf target
    cp -R target-cached target
```

**Comment by frewsxcv** [comment]
Actually that's probably not good since features could have a ton of dependencies. Maybe the first line should be `cargo build --all-features`. Hmm

**Comment by Manishearth** [comment]
yeah the thing is that all of that is doable, but chunking kinda lets you do much the same without as many nuances

**Comment by Manishearth** [comment]
_okay so_ there's actually a bug in `cargo-all-features` here wrt the new dependency stuff, `skip_optional_dependencies` isn't working

**Comment by Manishearth** [comment]
Yeah, `cargo metadata` unconditionally generates a `"foo": ["dep:foo"]` entry for each optional dependency. Gonna fixup the code here.

**Comment by Manishearth** [comment]
(is there a reason this crate isn't using serde-json and/or clap?)

**Comment by Manishearth** [comment]
https://github.com/frewsxcv/cargo-all-features/issues/29

**Comment by sffc** [comment]
Another option here would be to just give a way to filter the return value of `determine_packages_to_test()` in workspaces.
